### PR TITLE
Update java-checks-6.1.1.xml

### PR DESCRIPTION
**Pull request by bryyoung**

### CODE REVIEW

**Comment by mikemarr** [comment]
Whats the difference between this file and the other `java-checks.xml`? That java-checks also has `caseindent` and `arrayinit` at 2.

**Comment by bryyoung** [comment]
java-checks.xml is @ThomHehl's personal version? I dunno - I just changed the one that I knew was being used by me and anyone else who followed Harold's original walkthrough to get it set up

**Comment by ThomHehl** [comment]
The differences were that one was created for eclipse and one for IntelliJ. They both ended up being the same, which is a little surprising.

:+1:

**Comment by mikemarr** [comment]
Do we need to update the other to include these changes? And is the
standard supposed to be 4 and we just generated one with 2?

**Comment by bryyoung** [comment]
Yes, it probably should be updated

The standard we agreed on is 4 spaces, I would assume that these 2 values were just overlooked on the initial generation

**Pull request merged**
